/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DashgridIndexImport } from './routes/dashgrid/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashgridIndexRoute = DashgridIndexImport.update({
  id: '/dashgrid/',
  path: '/dashgrid/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashgrid/': {
      id: '/dashgrid/'
      path: '/dashgrid'
      fullPath: '/dashgrid'
      preLoaderRoute: typeof DashgridIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashgrid': typeof DashgridIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashgrid': typeof DashgridIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashgrid/': typeof DashgridIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashgrid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashgrid'
  id: '__root__' | '/' | '/dashgrid/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashgridIndexRoute: typeof DashgridIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashgridIndexRoute: DashgridIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashgrid/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashgrid/": {
      "filePath": "dashgrid/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
